/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.sergiotepaz.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.sergiotepaz.controlador.ControlDeVenta;
import org.sergiotepaz.modelo.Venta;

/**
 * Vista que contiene el historial de ventas
 * @author Sergio Tepaz
 * @version 1.8
 */
public class HistorialVentas extends javax.swing.JInternalFrame {
    
    public ControlDeVenta controlador = ControlDeVenta.getInstancia();

    /**
     * Creates new form HistorialVentas
     */
    public HistorialVentas() {
        initComponents();
    }
    
    public void mostrarDatosDeVentas(){
        String [] encabezados = {"Id de compra"," Id de cliente "," Id de cliente ","Cantidad","Fecha"};
        int CantidadDeElementos = controlador.ListaDeVentas();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,CantidadDeElementos);    
        tablaDeVentas.setModel(cabecera);
        TableModel ventas = tablaDeVentas.getModel();
        
        for(int i=0; i<CantidadDeElementos; i++){
            Venta venta = new Venta();
            venta = controlador.mostrarVentas().get(i);
            tablaDeVentas.setValueAt(venta.getId_venta(), i, 0);
            tablaDeVentas.setValueAt(venta.getId_producto(), i, 1);
            tablaDeVentas.setValueAt(venta.getId_cliente(), i,2);
            tablaDeVentas.setValueAt(venta.getCantidad(), i, 3);
            tablaDeVentas.setValueAt(venta.getFecha(), i, 4);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeVentas = new javax.swing.JTable();

        setBorder(null);

        tablaDeVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id de compra", "Id de cliente", "Id de producto", "Cantidad", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tablaDeVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDeVentas;
    // End of variables declaration//GEN-END:variables
}
