/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.sergiotepaz.vista;

/**
 * Ventana de cliente
 * @author Sergio Tepaz
 * @version 1.8
 */
public class VentanaCliente extends javax.swing.JFrame {
    
    private VerProductos instanciaVerProductos = null;
    private VistaVenta instanciaVistaVenta = null;
    private HistorialVentas instanciaHistorialVentas = null;

    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
        initComponents();
    }
    
    public synchronized VerProductos getInstanciaVerProductos(){
        if( instanciaVerProductos == null){
            instanciaVerProductos = new VerProductos();
            panel.add(instanciaVerProductos);
        } else if( instanciaVerProductos.isVisible() == false )
            instanciaVerProductos.setVisible(true);
        instanciaVerProductos.show();
        return instanciaVerProductos;
    }
    
    public synchronized VistaVenta getInstanciaVistaVenta(){
        if( instanciaVistaVenta == null){
            instanciaVistaVenta = new VistaVenta();
            panel.add(instanciaVistaVenta);
        } else if( instanciaVistaVenta.isVisible() == false )
            instanciaVistaVenta.setVisible(true);
        instanciaVistaVenta.show();
        return instanciaVistaVenta;
    }
    
     public synchronized HistorialVentas getInstanciaHistorialVentas(){
        if( instanciaHistorialVentas == null){
            instanciaHistorialVentas = new HistorialVentas();
            panel.add(instanciaHistorialVentas);
        } else if( instanciaHistorialVentas.isVisible() == false )
            instanciaHistorialVentas.setVisible(true);
        instanciaHistorialVentas.show();
        return instanciaHistorialVentas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        btnRegresar = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuProductos = new javax.swing.JMenu();
        VerProductos = new javax.swing.JMenuItem();
        ComprarProductos = new javax.swing.JMenuItem();
        MenuHistorial = new javax.swing.JMenu();
        Historial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        panel.setLayer(btnRegresar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(805, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(17, 17, 17))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(568, Short.MAX_VALUE))
        );

        MenuProductos.setText("Productos");

        VerProductos.setText("Ver Productos");
        VerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProductosActionPerformed(evt);
            }
        });
        MenuProductos.add(VerProductos);

        ComprarProductos.setText("Comprar Productos");
        ComprarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarProductosActionPerformed(evt);
            }
        });
        MenuProductos.add(ComprarProductos);

        MenuPrincipal.add(MenuProductos);

        MenuHistorial.setText("Historial");

        Historial.setText("Historial de compras");
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });
        MenuHistorial.add(Historial);

        MenuPrincipal.add(MenuHistorial);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void VerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProductosActionPerformed
        // TODO add your handling code here:
        getInstanciaVerProductos();
        instanciaVerProductos.mostrarDatosDeProductos();
    }//GEN-LAST:event_VerProductosActionPerformed

    private void ComprarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarProductosActionPerformed
        // TODO add your handling code here:
        getInstanciaVistaVenta();
    }//GEN-LAST:event_ComprarProductosActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        // TODO add your handling code here:
        getInstanciaHistorialVentas();
        instanciaHistorialVentas.mostrarDatosDeVentas();    
    }//GEN-LAST:event_HistorialActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ComprarProductos;
    private javax.swing.JMenuItem Historial;
    private javax.swing.JMenu MenuHistorial;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuProductos;
    private javax.swing.JMenuItem VerProductos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables
}
