/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.sergiotepaz.vista;

import java.awt.Graphics;

/**
 * Ventana de administrador con los CRUD
 * @author Sergio Tepaz
 * @version 1.8
 */
public class VentanaAdministradror extends javax.swing.JFrame {
    
    private  VistaCliente instanciaCliente = null;
    private  VistaUsuario instanciaUsuario = null;
    private  VistaProveedor instanciaProveedor = null;
    private  VistaProducto instanciaProducto = null;
    private  VistaCompra instanciaCompra = null;
   
    /**
     * Creates new form VentanaAdministradror
     */
    public VentanaAdministradror() {
        initComponents();
        lookAndFeel();
        this.setLocationRelativeTo(null);
    }
    
    public void lookAndFeel() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministradror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministradror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministradror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministradror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    
    public synchronized VistaCliente getInstanciaCliente(){
        if( instanciaCliente == null){
            instanciaCliente = new VistaCliente();
            panel.add(instanciaCliente);
        } else if( instanciaCliente.isVisible() == false )
            instanciaCliente.setVisible(true);
        instanciaCliente.show();
        return instanciaCliente;
    }
    
    public synchronized VistaUsuario getInstanciaUsuario() {
         if(instanciaUsuario == null){
            instanciaUsuario = new VistaUsuario();
            panel.add(instanciaUsuario);
        } else if( instanciaUsuario.isVisible() == false )
            instanciaUsuario.setVisible(true);
        instanciaUsuario.show();
        return instanciaUsuario;
    }
    
    public synchronized VistaProveedor getInstanciaProveedor() {
         if(instanciaProveedor == null){
            instanciaProveedor = new VistaProveedor();
            panel.add(instanciaProveedor);
        } else if( instanciaProveedor.isVisible() == false )
            instanciaProveedor.setVisible(true);
        instanciaProveedor.show();
        return instanciaProveedor;
    }
    
    public synchronized VistaProducto getInstanciaProducto() {
         if(instanciaProducto == null){
            instanciaProducto = new VistaProducto();
            panel.add(instanciaProducto);
        } else if( instanciaProducto.isVisible() == false )
            instanciaProducto.setVisible(true);
        instanciaProducto.show();
        return instanciaProducto;
    }
    
    public synchronized VistaCompra getInstanciaCompra() {
         if(instanciaCompra == null){
            instanciaCompra = new VistaCompra();
            panel.add(instanciaCompra);
        } else if( instanciaCompra.isVisible() == false )
            instanciaCompra.setVisible(true);
        instanciaCompra.show();
        return instanciaCompra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        btnRegresar = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuCliente = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        MenuUsuario = new javax.swing.JMenu();
        Usuario = new javax.swing.JMenuItem();
        MenuProveedor = new javax.swing.JMenu();
        Proveedor = new javax.swing.JMenuItem();
        MenuProducto = new javax.swing.JMenu();
        Producto = new javax.swing.JMenuItem();
        MenuCompra = new javax.swing.JMenu();
        Compra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnRegresar.setBackground(new java.awt.Color(0, 102, 204));
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        panel.setLayer(btnRegresar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(867, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(15, 15, 15))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        MenuCliente.setText("Cliente");

        Cliente.setText("Menu Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        MenuCliente.add(Cliente);

        MenuPrincipal.add(MenuCliente);

        MenuUsuario.setText("Usuario");

        Usuario.setText("Menu Usuario");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        MenuUsuario.add(Usuario);

        MenuPrincipal.add(MenuUsuario);

        MenuProveedor.setText("Proveedor");

        Proveedor.setText("Menu Proveedor");
        Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorActionPerformed(evt);
            }
        });
        MenuProveedor.add(Proveedor);

        MenuPrincipal.add(MenuProveedor);

        MenuProducto.setText("Producto");

        Producto.setText("Menu Producto");
        Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoActionPerformed(evt);
            }
        });
        MenuProducto.add(Producto);

        MenuPrincipal.add(MenuProducto);

        MenuCompra.setText("Compra");

        Compra.setText("Menu Compra");
        Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraActionPerformed(evt);
            }
        });
        MenuCompra.add(Compra);

        MenuPrincipal.add(MenuCompra);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
        getInstanciaCliente();
    }//GEN-LAST:event_ClienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
        getInstanciaUsuario();
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorActionPerformed
        // TODO add your handling code here:
        getInstanciaProveedor();
    }//GEN-LAST:event_ProveedorActionPerformed

    private void ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoActionPerformed
        // TODO add your handling code here:
        getInstanciaProducto();
    }//GEN-LAST:event_ProductoActionPerformed

    private void CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraActionPerformed
        // TODO add your handling code here:
        getInstanciaCompra();
        
    }//GEN-LAST:event_CompraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenuItem Compra;
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuCompra;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu MenuProducto;
    private javax.swing.JMenu MenuProveedor;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JMenuItem Producto;
    private javax.swing.JMenuItem Proveedor;
    private javax.swing.JMenuItem Usuario;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables
}
