/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.sergiotepaz.vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import  org.sergiotepaz.modelo.Producto;
import  org.sergiotepaz.controlador.ControlDeProducto;

/**
 * JInternalFrame para la opcion de ver productos
 * @author Sergio Tepaz
 * @version 1.8
 */

public class VerProductos extends javax.swing.JInternalFrame {

   public ControlDeProducto controlador = ControlDeProducto.getInstancia();
    /**
     * Creates new form VistaVerCliente
     */
    public VerProductos() {
        initComponents();
    }
    
    /**
     * Muestra los datos agregados en VistaAgregarCliente
     */
    public void mostrarDatosDeProductos(){
        String [] encabezados = {" Id Producto "," Id Proveedor ","Producto,","Precio"};
        int CantidadDeElementos = controlador.ListaDeProductos();
        
        DefaultTableModel cabecera = new DefaultTableModel(encabezados,CantidadDeElementos);    
        tablaDeProductos.setModel(cabecera);
        TableModel productos = tablaDeProductos.getModel();
        
        for(int i=0; i<CantidadDeElementos; i++){
            Producto producto = new Producto();
            producto = controlador.mostrarProductos().get(i);
            tablaDeProductos.setValueAt(producto.getId_producto(), i, 0);
            tablaDeProductos.setValueAt(producto.getId_proveedor(), i,1);
            tablaDeProductos.setValueAt(producto.getProducto(), i, 2);
            tablaDeProductos.setValueAt(producto.getPrecio(), i, 3);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelTablaDeClientes = new javax.swing.JScrollPane();
        tablaDeProductos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tablaDeProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Producto", "Id Proveedor", "Producto", "Precio"
            }
        ));
        scrollPanelTablaDeClientes.setViewportView(tablaDeProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelTablaDeClientes)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPanelTablaDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelTablaDeClientes;
    private javax.swing.JTable tablaDeProductos;
    // End of variables declaration//GEN-END:variables
}
